### ISSUE TITLE
Tab headings appear at top of preview

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/adobe-markdown-authoring#24]
If tab syntax appears on the page, the tab labels appear at the top of preview. Example:

![Screenshot 2023-03-21 at 10 15 05 AM](https://user-images.githubusercontent.com/6193209/226689977-6fe019b4-d1e9-4447-b1f8-daa014120d28.png)

CC: @geverit4

**Comment by geverit4** [comment]
This item was addressed in a previous build.  

![Screenshot 2023-04-11 at 7 52 21 PM](https://user-images.githubusercontent.com/1187616/231313383-c2e001f5-6b9b-43a2-9fde-b6367fac8cc0.png)

**Comment by bbringhu** [comment]
@geverit4 - I'm still seeing the tabs at the top of preview.

![Screenshot 2023-04-12 at 9 56 23 AM](https://user-images.githubusercontent.com/6193209/231528722-9617af0a-b05b-4898-a39d-bed330dca9ac.png)

**Comment by geverit4** [comment]
@bbringhu can you attach a test document?  I can't break it :)

**Comment by bbringhu** [comment]
Here's a test document.

[syntax-style-guide.md](https://github.com/AdobeDocs/adobe-markdown-authoring/files/11215306/syntax-style-guide.md)

**Comment by geverit4** [comment]
I was able to reproduce the problem.  It was quite pernicious.  Only happened when there were other blockquotes in the document.  It works in my test document, but doesn't display well in your test document - so I still need to do a bit more investigation.

**Comment by geverit4** [comment]
In my test document:
![Screenshot 2023-04-12 at 6 44 09 PM](https://user-images.githubusercontent.com/1187616/231602407-8f948243-85dc-44fa-8148-04743f24f873.png)

Same tabs in yours: 
![Screenshot 2023-04-12 at 6 45 02 PM](https://user-images.githubusercontent.com/1187616/231602547-f5ced250-b1eb-4ff0-84da-9664ab4c1d4a.png)

**Comment by bbringhu** [comment]
Sounds like an edge case.

**Comment by geverit4** [comment]
Yeah - but it's a big fat edge, though.  It happens only when other "blockquote" tokens are in the document, which is pretty much all of AFM.  My test document only had the tabs section. As soon as I added a `>[!TIP]` everything went all cattywampus.

**Comment by geverit4** [comment]
@bbringhu do you have a link to the version of the style guide that is available to me?  When I click on https://experienceleague.adobe.com/docs/authoring-guide-exl/using/markdown/syntax-style-guide.html?lang=en#tabs

It redirects me to the corp site, which I cannot access:  https://experienceleague.corp.adobe.com/docs/authoring-guide-exl/using/markdown/syntax-style-guide.html?lang=en#tabs

Everything looks right now, except the tab contents are not displaying.  It's not clear what's wrong from examining the output HTML.

![Screenshot 2023-04-13 at 3 52 44 PM](https://user-images.githubusercontent.com/1187616/231868673-454dee94-456f-458b-a782-acbc42e09cff.png)

**Comment by geverit4** [comment]
Here's a capture of what the HTML output looks like: 

```html
<div class="sp-wrapper"><sp-tabs selected="1" size="l" direction="horizontal" dir="ltr" focusable=""><div></div>
<sp-tab label="iOS" value="1" dir="ltr" role="tab" id="sp-tab-1" aria-selected="true" tabindex="0" aria-controls="sp-tab-panel-1" selected=""></sp-tab><div></div>
<sp-tab label="Android" value="2" dir="ltr" role="tab" id="sp-tab-2" aria-selected="false" tabindex="-1" aria-controls="sp-tab-panel-2"></sp-tab><div></div>
<sp-tab label="Windows" value="3" dir="ltr" role="tab" id="sp-tab-3" aria-selected="false" tabindex="-1" aria-controls="sp-tab-panel-3"></sp-tab><div></div>
<sp-tab label="MacOS" value="4" dir="ltr" role="tab" id="sp-tab-4" aria-selected="false" tabindex="-1" aria-controls="sp-tab-panel-4"></sp-tab><div></div>
<sp-tab label="Linux" value="5" dir="ltr" role="tab" id="sp-tab-5" aria-selected="false" tabindex="-1" aria-controls="sp-tab-panel-5"></sp-tab><div></div>
</sp-tabs><div></div>
<sp-tab-panel value="1" dir="ltr" slot="tab-panel" role="tabpanel" tabindex="-1" id="sp-tab-panel-0" aria-labelledby="sp-tab-0" aria-hidden="true"><div style="display:block !important"><p data-line="18" class="code-line" dir="auto">This content appears in the iOS tab.</p>
<div></div>
</div></sp-tab-panel><div></div>
<sp-tab-panel value="2" dir="ltr" slot="tab-panel" role="tabpanel" tabindex="-1" id="sp-tab-panel-1" aria-labelledby="sp-tab-1" aria-hidden="true"><div style="display:block !important"><p data-line="22" class="code-line" dir="auto">This content appears in the Android tab.</p>
<div></div>
</div></sp-tab-panel><div></div>
<sp-tab-panel value="3" dir="ltr" slot="tab-panel" role="tabpanel" tabindex="-1" id="sp-tab-panel-2" aria-labelledby="sp-tab-2" aria-hidden="true"><div style="display:block !important"><p data-line="26" class="code-line" dir="auto">This content appears in the Windows tab.</p>
<div></div>
</div></sp-tab-panel><div></div>
<sp-tab-panel value="4" dir="ltr" slot="tab-panel" role="tabpanel" tabindex="-1" id="sp-tab-panel-3" aria-labelledby="sp-tab-3" aria-hidden="true"><div style="display:block !important"><p data-line="30" class="code-line" dir="auto">This content appears in the MacOS tab.</p>
<div></div>
</div></sp-tab-panel><div></div>
<sp-tab-panel value="5" dir="ltr" slot="tab-panel" role="tabpanel" tabindex="-1" id="sp-tab-panel-4" aria-labelledby="sp-tab-4" aria-hidden="true"><div style="display:block !important"><p data-line="34" class="code-line" dir="auto">This content appears in the Linux tab.</p>
<div></div>
</div></sp-tab-panel><div></div>
</div>
```

**Comment by geverit4** [comment]
@bbringhu I figured it out.  I wasn't ending </sp-tabs> properly. Although, it wouldn't hurt to have a link to the new syntax style guide.  

![Screenshot 2023-04-13 at 4 04 45 PM](https://user-images.githubusercontent.com/1187616/231871058-341698aa-98f1-49d2-9e45-327a38c836dd.png)

**Comment by bbringhu** [comment]
> @bbringhu I figured it out. I wasn't ending properly. Although, it wouldn't hurt to have a link to the new syntax style guide.

https://git.corp.adobe.com/AdobeDocs/authoring-guide-exl.en/blob/main/help/main-guide/syntax-style-guide.md

Here's the .md file itself in case you can't access the enterprise Git link:

[syntax-style-guide.md](https://github.com/AdobeDocs/adobe-markdown-authoring/files/11226445/syntax-style-guide.md)

**Comment by bbringhu** [comment]
Confirmed fixed in 2.0.5
